import type { Category, Product } from "./types"

// Base URL for the Express backend
const API_URL = process.env.NEXT_PUBLIC_API_URL || "https://localhost:3001"

// Function to fetch categories
export async function getCategories(): Promise<Category[]> {
  const response = await fetch(`${API_URL}/api/categories`)

  if (!response.ok) {
    throw new Error("Failed to fetch categories")
  }

  return response.json()
}

// Function to fetch products by category
export async function getProductsByCategory(categorySlug: string): Promise<Product[]> {
  const response = await fetch(`${API_URL}/api/products?category=${categorySlug}`)

  if (!response.ok) {
    throw new Error(`Failed to fetch products for category: ${categorySlug}`)
  }

  return response.json()
}

// Function to search products
export async function searchProducts(query: string): Promise<Product[]> {
  // For demo purposes, we'll return mock data
  // In a real app, this would call the API
  if (query.toLowerCase().includes("iphone14") || query.toLowerCase().includes("iphone 14")) {
    return iphone14Products
  }

  return mockProducts.filter(
    (product) =>
      product.name.toLowerCase().includes(query.toLowerCase()) ||
      product.category.toLowerCase().includes(query.toLowerCase()),
  )
}

// Function to get product details
export async function getProductById(productId: number): Promise<Product> {
  // For demo purposes, we'll return mock data
  // In a real app, this would call the API
  const allProducts = [...mockProducts, ...iphone14Products]
  const product = allProducts.find((p) => p.id === productId)

  if (!product) {
    throw new Error(`Product with ID ${productId} not found`)
  }

  return product
}

// Mock products for demo
const mockProducts: Product[] = [
  {
    id: 1,
    name: "Amazon Echo Buds with Active Noise Cancellation (newest model), Wireless Earbuds",
    price: 129.99,
    originalPrice: 149.99,
    imageUrl: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=300&width=300",
      "/placeholder.svg?height=300&width=300",
      "/placeholder.svg?height=300&width=300",
    ],
    category: "headphones",
    rating: 3.6,
    reviews: 1000,
    purchases: "1K+ bought in past month",
    brand: "Amazon",
    colors: ["White", "Black", "Navy"],
    features: [
      "Active Noise Cancellation blocks external sounds",
      "Compact and lightweight design for all-day comfort",
      "Up to 5 hours of music playback per charge",
      "Alexa voice control for hands-free operation",
    ],
    freeDelivery: true,
    deliveryDate: "Tomorrow",
    sustainability: 1,
    description: "Experience premium sound quality and active noise cancellation with the all-new Amazon Echo Buds.",
    condition: "New",
    seller: {
      id: 1,
      name: "AMAZON OFFICIAL",
      feedback: 99.8,
      joined: "Jan 2010",
      responseTime: "Usually responds within 24 hours",
      description: "Official Amazon store. All products are brand new and come with full manufacturer warranty.",
    },
  },
  {
    id: 2,
    name: "JBL Tune 510BT - Bluetooth headphones with up to 40 hours battery, microphone for calls",
    price: 25.38,
    originalPrice: 49.95,
    imageUrl: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=300&width=300",
      "/placeholder.svg?height=300&width=300",
      "/placeholder.svg?height=300&width=300",
    ],
    category: "headphones",
    rating: 4.5,
    reviews: 75900,
    purchases: "10K+ bought in past month",
    badge: "Best Seller",
    colors: ["Black", "Blue", "White", "Pink"],
    features: [
      "Wireless Bluetooth 5.0 Streaming",
      "JBL Pure Bass Sound",
      "40 hours of battery life",
      "Multi-Point Connection",
      "Lightweight and foldable design",
    ],
    freeDelivery: true,
    deliveryDate: "Tuesday, May 28",
    description: "Enjoy JBL Pure Bass Sound with these wireless headphones featuring up to 40 hours of battery life.",
    condition: "New",
    seller: {
      id: 2,
      name: "JBL OFFICIAL STORE",
      feedback: 99.5,
      joined: "Mar 2015",
      responseTime: "Usually responds within 24 hours",
      description: "Official JBL store. All products are brand new and come with full manufacturer warranty.",
    },
  },
  {
    id: 3,
    name: "Sony WH-CH720N Noise Canceling Wireless Headphones Bluetooth Over-Ear Headset",
    price: 128.0,
    originalPrice: 149.99,
    imageUrl: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=300&width=300",
      "/placeholder.svg?height=300&width=300",
      "/placeholder.svg?height=300&width=300",
    ],
    category: "headphones",
    rating: 4.4,
    reviews: 9800,
    purchases: "9K+ bought in past month",
    badge: "Overall Pick",
    colors: ["Black", "Blue", "White"],
    features: [
      "Digital Noise Cancellation",
      "Up to 35 hours of battery life with Noise Canceling on",
      "Multipoint connection - connect to two Bluetooth devices at the same time",
      "Built-in microphone for hands-free calls",
      "Comfortable and lightweight design",
    ],
    freeDelivery: true,
    deliveryDate: "Wednesday, May 29",
    description:
      "Experience premium sound quality with Sony's noise canceling technology that adapts to your environment.",
    condition: "New",
    seller: {
      id: 3,
      name: "SONY ELECTRONICS",
      feedback: 99.7,
      joined: "Apr 2012",
      responseTime: "Usually responds within 24 hours",
      description:
        "Official Sony Electronics store. All products are brand new and come with full manufacturer warranty.",
    },
  },
  {
    id: 4,
    name: "Sony WH-1000XM4 Wireless Premium Noise Canceling Overhead Headphones with Mic",
    price: 298.0,
    originalPrice: 348.0,
    imageUrl: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=300&width=300",
      "/placeholder.svg?height=300&width=300",
      "/placeholder.svg?height=300&width=300",
    ],
    category: "headphones",
    rating: 4.6,
    reviews: 59700,
    purchases: "4K+ bought in past month",
    colors: ["Black", "Blue", "Silver"],
    features: [
      "Industry-leading noise cancellation",
      "Premium sound quality with Edge-AI",
      "Up to 30 hours battery life",
      "Touch controls for easy operation",
      "Speak-to-chat technology automatically reduces volume during conversations",
      "Wearing detection pauses playback when headphones are removed",
    ],
    freeDelivery: true,
    deliveryDate: "Tuesday, May 27",
    description: "Sony's flagship headphones with industry-leading noise cancellation and exceptional sound quality.",
    condition: "New",
    seller: {
      id: 3,
      name: "SONY ELECTRONICS",
      feedback: 99.7,
      joined: "Apr 2012",
      responseTime: "Usually responds within 24 hours",
      description:
        "Official Sony Electronics store. All products are brand new and come with full manufacturer warranty.",
    },
  },
  {
    id: 5,
    name: "Picun B8 Bluetooth Headphones, 120H Playtime Headphone Wireless Over Ear with Deep Bass",
    price: 16.99,
    originalPrice: 29.99,
    imageUrl: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=300&width=300",
      "/placeholder.svg?height=300&width=300",
      "/placeholder.svg?height=300&width=300",
    ],
    category: "headphones",
    rating: 4.6,
    reviews: 5300,
    purchases: "8K+ bought in past month",
    colors: ["Black", "Gray", "Mint", "Beige", "Red", "Blue"],
    features: [
      "120 Hours Playtime with Fast Charging",
      "Hi-Fi Stereo Sound with Deep Bass",
      "Bluetooth 5.3 for stable connection",
      "Memory-protein earpads for comfort",
      "Built-in microphone for calls",
      "Foldable design for easy storage",
    ],
    freeDelivery: true,
    deliveryDate: "Saturday, May 24",
    description: "Affordable wireless headphones with impressive 120-hour battery life and comfortable design.",
    condition: "New",
    seller: {
      id: 4,
      name: "PICUN OFFICIAL",
      feedback: 98.2,
      joined: "Sep 2018",
      responseTime: "Usually responds within 24 hours",
      description: "Official Picun store. All products are brand new and come with full manufacturer warranty.",
    },
  },
]

// iPhone 14 mock products
const iphone14Products: Product[] = [
  {
    id: 101,
    name: "Apple iPhone 14 Pro Max, 128GB, Deep Purple, Unlocked",
    price: 999.99,
    originalPrice: 1099.99,
    originalCurrency: "GBP",
    imageUrl: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=300&width=300",
      "/placeholder.svg?height=300&width=300",
      "/placeholder.svg?height=300&width=300",
      "/placeholder.svg?height=300&width=300",
    ],
    category: "smartphones",
    rating: 4.8,
    reviews: 12543,
    purchases: "5K+ bought in past month",
    badge: "Top Rated",
    brand: "Apple",
    colors: ["Deep Purple", "Gold", "Silver", "Space Black"],
    storage: ["128GB", "256GB", "512GB", "1TB"],
    features: [
      "6.7-inch Super Retina XDR display with ProMotion",
      "A16 Bionic chip",
      "Pro camera system (48MP Main, 12MP Ultra Wide, 12MP Telephoto)",
      "Action mode for smooth, steady handheld videos",
      "All-day battery life and up to 29 hours of video playback",
      "Face ID for secure authentication",
    ],
    shipping: 15.99,
    estimatedDelivery: "Wed, May 28 - Fri, May 30",
    description:
      "The iPhone 14 Pro Max. Pro. Beyond. Featuring the Always-On display, the first-ever 48MP camera on iPhone, and the Dynamic Island, a truly Apple innovation that's hardware and software and something in between.",
    condition: "Very Good - Refurbished",
    conditionDescription: "These devices are in a very good cond...",
    sold: 27,
    available: 10,
    itemNumber: "387826473294",
    processor: "Hexa-core (2x3.23 GHz Avalanche + 4x1.82 GHz Blizzard)",
    watchers: 64,
    seller: {
      id: 5,
      name: "COV PHONES",
      feedback: 98.6,
      joined: "Feb 2020",
      responseTime: "Usually responds within 24 hours",
      description:
        "We are a mobile phone refurbishing business based in the UK. We refurbish our phone to a very high standard.HIGH-QUALITY PRODUCT-Professionally inspected, tested by qualified Level 4 Engineers. These phones are in excellent working order. Certify With Phone-check: The most trusted certification in the used device market.",
      totalFeedback: "3,411",
      feedbackCount: "402",
    },
  },
  {
    id: 102,
    name: "Apple iPhone 14, 128GB, Blue, Unlocked",
    price: 799.99,
    originalPrice: 899.99,
    originalCurrency: "GBP",
    imageUrl: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=300&width=300",
      "/placeholder.svg?height=300&width=300",
      "/placeholder.svg?height=300&width=300",
    ],
    category: "smartphones",
    rating: 4.7,
    reviews: 9876,
    purchases: "4K+ bought in past month",
    brand: "Apple",
    colors: ["Blue", "Purple", "Midnight", "Starlight", "Red"],
    storage: ["128GB", "256GB", "512GB"],
    features: [
      "6.1-inch Super Retina XDR display",
      "A15 Bionic chip with 5-core GPU",
      "Advanced camera system with improved Night mode",
      "Cinematic mode in 4K Dolby Vision up to 30 fps",
      "Up to 20 hours of video playback",
      "Face ID for secure authentication",
    ],
    shipping: 12.99,
    estimatedDelivery: "Tue, May 27 - Thu, May 29",
    description:
      "The iPhone 14. A total powerhouse. With a new dual-camera system for better photos in any light. Crash Detection, a safety feature that calls for help when you can't. And incredible battery life.",
    condition: "Excellent - Refurbished",
    conditionDescription: "These devices are in excellent condition with minimal signs of use.",
    sold: 35,
    available: 15,
    itemNumber: "387826473295",
    processor: "Hexa-core (2x3.23 GHz Avalanche + 4x1.82 GHz Blizzard)",
    watchers: 78,
    seller: {
      id: 5,
      name: "COV PHONES",
      feedback: 98.6,
      joined: "Feb 2020",
      responseTime: "Usually responds within 24 hours",
      description:
        "We are a mobile phone refurbishing business based in the UK. We refurbish our phone to a very high standard.HIGH-QUALITY PRODUCT-Professionally inspected, tested by qualified Level 4 Engineers. These phones are in excellent working order. Certify With Phone-check: The most trusted certification in the used device market.",
      totalFeedback: "3,411",
      feedbackCount: "402",
    },
  },
  {
    id: 103,
    name: "Apple iPhone 14 Pro, 256GB, Space Black, Unlocked",
    price: 949.99,
    originalPrice: 1049.99,
    originalCurrency: "GBP",
    imageUrl: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=300&width=300",
      "/placeholder.svg?height=300&width=300",
      "/placeholder.svg?height=300&width=300",
    ],
    category: "smartphones",
    rating: 4.9,
    reviews: 8765,
    purchases: "3K+ bought in past month",
    badge: "Top Rated",
    brand: "Apple",
    colors: ["Space Black", "Silver", "Gold", "Deep Purple"],
    storage: ["128GB", "256GB", "512GB", "1TB"],
    features: [
      "6.1-inch Super Retina XDR display with ProMotion",
      "A16 Bionic chip",
      "Pro camera system (48MP Main, 12MP Ultra Wide, 12MP Telephoto)",
      "Action mode for smooth, steady handheld videos",
      "All-day battery life and up to 23 hours of video playback",
      "Face ID for secure authentication",
    ],
    shipping: 14.99,
    estimatedDelivery: "Wed, May 28 - Fri, May 30",
    description:
      "The iPhone 14 Pro. Pro. Beyond. Featuring the Always-On display, the first-ever 48MP camera on iPhone, and the Dynamic Island, a truly Apple innovation that's hardware and software and something in between.",
    condition: "Very Good - Refurbished",
    conditionDescription: "These devices are in a very good condition with minor signs of use.",
    sold: 42,
    available: 8,
    itemNumber: "387826473296",
    processor: "Hexa-core (2x3.23 GHz Avalanche + 4x1.82 GHz Blizzard)",
    watchers: 92,
    seller: {
      id: 6,
      name: "TECH REVIVE",
      feedback: 99.2,
      joined: "Mar 2019",
      responseTime: "Usually responds within 12 hours",
      description:
        "We specialize in premium refurbished Apple products. All our devices undergo a rigorous 50-point inspection process and come with a 12-month warranty.",
      totalFeedback: "5,287",
      feedbackCount: "623",
    },
  },
  {
    id: 104,
    name: "Apple iPhone 14 Plus, 128GB, Starlight, Unlocked",
    price: 899.99,
    originalPrice: 999.99,
    originalCurrency: "GBP",
    imageUrl: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=300&width=300",
      "/placeholder.svg?height=300&width=300",
      "/placeholder.svg?height=300&width=300",
    ],
    category: "smartphones",
    rating: 4.6,
    reviews: 5432,
    purchases: "2K+ bought in past month",
    brand: "Apple",
    colors: ["Starlight", "Midnight", "Blue", "Purple", "Red"],
    storage: ["128GB", "256GB", "512GB"],
    features: [
      "6.7-inch Super Retina XDR display",
      "A15 Bionic chip with 5-core GPU",
      "Advanced camera system with improved Night mode",
      "Cinematic mode in 4K Dolby Vision up to 30 fps",
      "Up to 26 hours of video playback",
      "Face ID for secure authentication",
    ],
    shipping: 12.99,
    estimatedDelivery: "Tue, May 27 - Thu, May 29",
    description:
      "The iPhone 14 Plus. A huge leap in battery life. A new Main camera and improved image processing to capture your shots in all kinds of light—especially low light. And Crash Detection, a safety feature that calls for help when you can't.",
    condition: "Good - Refurbished",
    conditionDescription: "These devices are in good working condition with some signs of normal use.",
    sold: 29,
    available: 12,
    itemNumber: "387826473297",
    processor: "Hexa-core (2x3.23 GHz Avalanche + 4x1.82 GHz Blizzard)",
    watchers: 56,
    seller: {
      id: 7,
      name: "MOBILE MASTERS",
      feedback: 97.8,
      joined: "Jun 2018",
      responseTime: "Usually responds within 24 hours",
      description:
        "We provide high-quality refurbished smartphones at competitive prices. All devices are thoroughly tested and come with a 6-month warranty.",
      totalFeedback: "2,845",
      feedbackCount: "356",
    },
  },
  {
    id: 105,
    name: "Apple iPhone 14 Pro Max, 512GB, Gold, Unlocked",
    price: 1199.99,
    originalPrice: 1299.99,
    originalCurrency: "GBP",
    imageUrl: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=300&width=300",
      "/placeholder.svg?height=300&width=300",
      "/placeholder.svg?height=300&width=300",
    ],
    category: "smartphones",
    rating: 4.8,
    reviews: 7654,
    purchases: "1K+ bought in past month",
    badge: "Premium",
    brand: "Apple",
    colors: ["Gold", "Silver", "Space Black", "Deep Purple"],
    storage: ["128GB", "256GB", "512GB", "1TB"],
    features: [
      "6.7-inch Super Retina XDR display with ProMotion",
      "A16 Bionic chip",
      "Pro camera system (48MP Main, 12MP Ultra Wide, 12MP Telephoto)",
      "Action mode for smooth, steady handheld videos",
      "All-day battery life and up to 29 hours of video playback",
      "Face ID for secure authentication",
    ],
    shipping: 0,
    estimatedDelivery: "Mon, May 26 - Wed, May 28",
    description:
      "The iPhone 14 Pro Max. Pro. Beyond. Featuring the Always-On display, the first-ever 48MP camera on iPhone, and the Dynamic Island, a truly Apple innovation that's hardware and software and something in between.",
    condition: "Like New - Refurbished",
    conditionDescription: "These devices are in like-new condition with no visible signs of use.",
    sold: 18,
    available: 5,
    itemNumber: "387826473298",
    processor: "Hexa-core (2x3.23 GHz Avalanche + 4x1.82 GHz Blizzard)",
    watchers: 103,
    seller: {
      id: 8,
      name: "APPLE PRO STORE",
      feedback: 99.5,
      joined: "Jan 2017",
      responseTime: "Usually responds within 8 hours",
      description:
        "Authorized Apple reseller specializing in premium refurbished Apple products. All devices undergo Apple's certified refurbishment process and come with a 1-year warranty.",
      totalFeedback: "8,932",
      feedbackCount: "1,245",
    },
  },
  {
    id: 106,
    name: "Apple iPhone 14, 256GB, Purple, Unlocked",
    price: 849.99,
    originalPrice: 949.99,
    originalCurrency: "GBP",
    imageUrl: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=300&width=300",
      "/placeholder.svg?height=300&width=300",
      "/placeholder.svg?height=300&width=300",
    ],
    category: "smartphones",
    rating: 4.7,
    reviews: 6543,
    purchases: "2K+ bought in past month",
    brand: "Apple",
    colors: ["Purple", "Blue", "Midnight", "Starlight", "Red"],
    storage: ["128GB", "256GB", "512GB"],
    features: [
      "6.1-inch Super Retina XDR display",
      "A15 Bionic chip with 5-core GPU",
      "Advanced camera system with improved Night mode",
      "Cinematic mode in 4K Dolby Vision up to 30 fps",
      "Up to 20 hours of video playback",
      "Face ID for secure authentication",
    ],
    shipping: 9.99,
    estimatedDelivery: "Thu, May 29 - Sat, May 31",
    description:
      "The iPhone 14. A total powerhouse. With a new dual-camera system for better photos in any light. Crash Detection, a safety feature that calls for help when you can't. And incredible battery life.",
    condition: "Excellent - Refurbished",
    conditionDescription: "These devices are in excellent condition with minimal signs of use.",
    sold: 31,
    available: 14,
    itemNumber: "387826473299",
    processor: "Hexa-core (2x3.23 GHz Avalanche + 4x1.82 GHz Blizzard)",
    watchers: 72,
    seller: {
      id: 5,
      name: "COV PHONES",
      feedback: 98.6,
      joined: "Feb 2020",
      responseTime: "Usually responds within 24 hours",
      description:
        "We are a mobile phone refurbishing business based in the UK. We refurbish our phone to a very high standard.HIGH-QUALITY PRODUCT-Professionally inspected, tested by qualified Level 4 Engineers. These phones are in excellent working order. Certify With Phone-check: The most trusted certification in the used device market.",
      totalFeedback: "3,411",
      feedbackCount: "402",
    },
  },
  {
    id: 107,
    name: "Apple iPhone 14 Pro, 128GB, Deep Purple, Unlocked",
    price: 899.99,
    originalPrice: 999.99,
    originalCurrency: "GBP",
    imageUrl: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=300&width=300",
      "/placeholder.svg?height=300&width=300",
      "/placeholder.svg?height=300&width=300",
    ],
    category: "smartphones",
    rating: 4.8,
    reviews: 7890,
    purchases: "3K+ bought in past month",
    badge: "Best Seller",
    brand: "Apple",
    colors: ["Deep Purple", "Gold", "Silver", "Space Black"],
    storage: ["128GB", "256GB", "512GB", "1TB"],
    features: [
      "6.1-inch Super Retina XDR display with ProMotion",
      "A16 Bionic chip",
      "Pro camera system (48MP Main, 12MP Ultra Wide, 12MP Telephoto)",
      "Action mode for smooth, steady handheld videos",
      "All-day battery life and up to 23 hours of video playback",
      "Face ID for secure authentication",
    ],
    shipping: 0,
    estimatedDelivery: "Tue, May 27 - Thu, May 29",
    description:
      "The iPhone 14 Pro. Pro. Beyond. Featuring the Always-On display, the first-ever 48MP camera on iPhone, and the Dynamic Island, a truly Apple innovation that's hardware and software and something in between.",
    condition: "Very Good - Refurbished",
    conditionDescription: "These devices are in a very good condition with minor signs of use.",
    sold: 45,
    available: 7,
    itemNumber: "387826473300",
    processor: "Hexa-core (2x3.23 GHz Avalanche + 4x1.82 GHz Blizzard)",
    watchers: 86,
    seller: {
      id: 6,
      name: "TECH REVIVE",
      feedback: 99.2,
      joined: "Mar 2019",
      responseTime: "Usually responds within 12 hours",
      description:
        "We specialize in premium refurbished Apple products. All our devices undergo a rigorous 50-point inspection process and come with a 12-month warranty.",
      totalFeedback: "5,287",
      feedbackCount: "623",
    },
  },
  {
    id: 108,
    name: "Apple iPhone 14 Plus, 256GB, Red, Unlocked",
    price: 949.99,
    originalPrice: 1049.99,
    originalCurrency: "GBP",
    imageUrl: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=300&width=300",
      "/placeholder.svg?height=300&width=300",
      "/placeholder.svg?height=300&width=300",
    ],
    category: "smartphones",
    rating: 4.6,
    reviews: 4321,
    purchases: "1K+ bought in past month",
    brand: "Apple",
    colors: ["Red", "Blue", "Purple", "Midnight", "Starlight"],
    storage: ["128GB", "256GB", "512GB"],
    features: [
      "6.7-inch Super Retina XDR display",
      "A15 Bionic chip with 5-core GPU",
      "Advanced camera system with improved Night mode",
      "Cinematic mode in 4K Dolby Vision up to 30 fps",
      "Up to 26 hours of video playback",
      "Face ID for secure authentication",
    ],
    shipping: 12.99,
    estimatedDelivery: "Wed, May 28 - Fri, May 30",
    description:
      "The iPhone 14 Plus. A huge leap in battery life. A new Main camera and improved image processing to capture your shots in all kinds of light—especially low light. And Crash Detection, a safety feature that calls for help when you can't.",
    condition: "Good - Refurbished",
    conditionDescription: "These devices are in good working condition with some signs of normal use.",
    sold: 24,
    available: 11,
    itemNumber: "387826473301",
    processor: "Hexa-core (2x3.23 GHz Avalanche + 4x1.82 GHz Blizzard)",
    watchers: 49,
    seller: {
      id: 7,
      name: "MOBILE MASTERS",
      feedback: 97.8,
      joined: "Jun 2018",
      responseTime: "Usually responds within 24 hours",
      description:
        "We provide high-quality refurbished smartphones at competitive prices. All devices are thoroughly tested and come with a 6-month warranty.",
      totalFeedback: "2,845",
      feedbackCount: "356",
    },
  },
  {
    id: 109,
    name: "Apple iPhone 14 Pro Max, 256GB, Silver, Unlocked",
    price: 1099.99,
    originalPrice: 1199.99,
    originalCurrency: "GBP",
    imageUrl: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=300&width=300",
      "/placeholder.svg?height=300&width=300",
      "/placeholder.svg?height=300&width=300",
    ],
    category: "smartphones",
    rating: 4.9,
    reviews: 6789,
    purchases: "2K+ bought in past month",
    badge: "Premium",
    brand: "Apple",
    colors: ["Silver", "Gold", "Space Black", "Deep Purple"],
    storage: ["128GB", "256GB", "512GB", "1TB"],
    features: [
      "6.7-inch Super Retina XDR display with ProMotion",
      "A16 Bionic chip",
      "Pro camera system (48MP Main, 12MP Ultra Wide, 12MP Telephoto)",
      "Action mode for smooth, steady handheld videos",
      "All-day battery life and up to 29 hours of video playback",
      "Face ID for secure authentication",
    ],
    shipping: 0,
    estimatedDelivery: "Mon, May 26 - Wed, May 28",
    description:
      "The iPhone 14 Pro Max. Pro. Beyond. Featuring the Always-On display, the first-ever 48MP camera on iPhone, and the Dynamic Island, a truly Apple innovation that's hardware and software and something in between.",
    condition: "Like New - Refurbished",
    conditionDescription: "These devices are in like-new condition with no visible signs of use.",
    sold: 21,
    available: 6,
    itemNumber: "387826473302",
    processor: "Hexa-core (2x3.23 GHz Avalanche + 4x1.82 GHz Blizzard)",
    watchers: 97,
    seller: {
      id: 8,
      name: "APPLE PRO STORE",
      feedback: 99.5,
      joined: "Jan 2017",
      responseTime: "Usually responds within 8 hours",
      description:
        "Authorized Apple reseller specializing in premium refurbished Apple products. All devices undergo Apple's certified refurbishment process and come with a 1-year warranty.",
      totalFeedback: "8,932",
      feedbackCount: "1,245",
    },
  },
  {
    id: 110,
    name: "Apple iPhone 14, 512GB, Midnight, Unlocked",
    price: 999.99,
    originalPrice: 1099.99,
    originalCurrency: "GBP",
    imageUrl: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=300&width=300",
      "/placeholder.svg?height=300&width=300",
      "/placeholder.svg?height=300&width=300",
    ],
    category: "smartphones",
    rating: 4.7,
    reviews: 5678,
    purchases: "1K+ bought in past month",
    brand: "Apple",
    colors: ["Midnight", "Blue", "Purple", "Starlight", "Red"],
    storage: ["128GB", "256GB", "512GB"],
    features: [
      "6.1-inch Super Retina XDR display",
      "A15 Bionic chip with 5-core GPU",
      "Advanced camera system with improved Night mode",
      "Cinematic mode in 4K Dolby Vision up to 30 fps",
      "Up to 20 hours of video playback",
      "Face ID for secure authentication",
    ],
    shipping: 9.99,
    estimatedDelivery: "Thu, May 29 - Sat, May 31",
    description:
      "The iPhone 14. A total powerhouse. With a new dual-camera system for better photos in any light. Crash Detection, a safety feature that calls for help when you can't. And incredible battery life.",
    condition: "Excellent - Refurbished",
    conditionDescription: "These devices are in excellent condition with minimal signs of use.",
    sold: 27,
    available: 9,
    itemNumber: "387826473303",
    processor: "Hexa-core (2x3.23 GHz Avalanche + 4x1.82 GHz Blizzard)",
    watchers: 68,
    seller: {
      id: 5,
      name: "COV PHONES",
      feedback: 98.6,
      joined: "Feb 2020",
      responseTime: "Usually responds within 24 hours",
      description:
        "We are a mobile phone refurbishing business based in the UK. We refurbish our phone to a very high standard.HIGH-QUALITY PRODUCT-Professionally inspected, tested by qualified Level 4 Engineers. These phones are in excellent working order. Certify With Phone-check: The most trusted certification in the used device market.",
      totalFeedback: "3,411",
      feedbackCount: "402",
    },
  },
]
