import type { Arbiter } from "@/lib/types"

export const mockArbiters: Arbiter[] = [
  {
    id: 1,
    name: "Ali H.",
    title: "Professional YouTube Video Editor",
    avatar: "/placeholder.svg?height=120&width=120",
    rating: 5.0,
    reviewCount: 20,
    jobSuccess: 100,
    hourlyRate: 20,
    isVerified: true,
    isAvailable: false,
    location: "Pakistan",
    localTime: "1:10 am",
    totalJobs: 24,
    totalHours: 43,
    totalEarned: "44K",
    skills: ["Video Editing", "Video Production", "Video Narration", "YouTube", "Video Editing & Production"],
    description:
      "I am a trained professional youtube video editor with an experience of 4 years. My demo reel includes working with various YouTube channels with over 1M+ subscribers.",
    buyerReviews: [
      {
        title: "Long Form Video Editing",
        rating: 5,
        date: "April 16, 2025",
        content:
          "Ali did a wonderful job editing our long-form YouTube video for us. A definite thumbs up, he was professional and exactly delivered to what our vision was regarding the video.",
        reviewer: "Shahzeb H.",
      },
      {
        title: "YouTube Channel Trailer",
        rating: 5,
        date: "March 10, 2025",
        content:
          "Excellent work on our channel trailer. Ali understood exactly what we needed and delivered high-quality work ahead of schedule.",
        reviewer: "Michael T.",
      },
    ],
    sellerReviews: [
      {
        title: "Great client to work with",
        rating: 5,
        date: "April 20, 2025",
        content: "Clear instructions and prompt communication. Would love to work with them again.",
        reviewer: "Ali H.",
      },
    ],
  },
  {
    id: 2,
    name: "Babar S.",
    title: "YouTube Video Editor",
    avatar: "/placeholder.svg?height=120&width=120",
    rating: 4.9,
    reviewCount: 15,
    jobSuccess: 91,
    hourlyRate: 10,
    isVerified: true,
    isAvailable: true,
    location: "Pakistan",
    localTime: "1:15 am",
    totalJobs: 18,
    totalHours: 35,
    totalEarned: "15K",
    skills: ["Adobe After Effects", "Adobe Premiere Pro", "Video Intro & Outro", "Video Editing"],
    description:
      "Hi, I'm Babar Sultan, a YouTube Video Editor and professional video editing expert with 5+ years of experience.",
    buyerReviews: [
      {
        title: "Video Editing for YouTube",
        rating: 5,
        date: "April 5, 2025",
        content:
          "Babar delivered excellent work on our YouTube video. Fast turnaround and great communication throughout the project.",
        reviewer: "James L.",
      },
    ],
    sellerReviews: [
      {
        title: "Excellent client",
        rating: 5,
        date: "March 25, 2025",
        content: "Clear requirements and prompt feedback. A pleasure to work with.",
        reviewer: "Babar S.",
      },
    ],
  },
  {
    id: 3,
    name: "Abdullah R.",
    title: "Professional YouTube Video Editor | Motion Graphics",
    avatar: "/placeholder.svg?height=120&width=120",
    rating: 4.9,
    reviewCount: 25,
    jobSuccess: 83,
    hourlyRate: 25,
    isVerified: false,
    isAvailable: true,
    location: "Lahore, Pakistan",
    localTime: "1:10 am",
    totalJobs: 24,
    totalHours: 43,
    totalEarned: "55K",
    skills: ["Adobe After Effects", "Adobe Premiere Pro", "Video Editing", "Adobe Photoshop"],
    description:
      "I specialize in video editing and Motion Graphics to enhance the online presence of e-commerce brands and various businesses. My work includes creating engaging content for YouTube channels and social media platforms.",
    buyerReviews: [
      {
        title: "Long Form Video Editing",
        rating: 5,
        date: "April 16, 2025",
        content:
          "Abdullah did a wonderful job editing our long-form YouTube video for us. A definite thumbs up, he was professional and exactly delivered to what our vision was regarding the video.",
        reviewer: "Shahzeb H.",
      },
      {
        title: "Experienced Video Editor Needed for YouTube Channel",
        rating: 5,
        date: "February 23, 2025 - March 19, 2025",
        content:
          "I am seeking a skilled video editor to enhance my YouTube channel content. The ideal candidate should have experience with Adobe Premiere Pro and be able to create engaging edits.",
        reviewer: "Client Name",
      },
    ],
    sellerReviews: [
      {
        title: "Great communication",
        rating: 5,
        date: "March 30, 2025",
        content: "The client was very clear about their requirements and provided timely feedback.",
        reviewer: "Abdullah R.",
      },
    ],
  },
  {
    id: 4,
    name: "Ojochegbe O.",
    title: "Youtube Video Editor and Voice Over Actor",
    avatar: "/placeholder.svg?height=120&width=120",
    rating: 5.0,
    reviewCount: 10,
    jobSuccess: 100,
    hourlyRate: 20,
    isVerified: true,
    isAvailable: false,
    location: "Nigeria",
    localTime: "11:10 pm",
    totalJobs: 11,
    totalHours: 28,
    totalEarned: "6K",
    skills: ["Video Editing", "Autodesk", "Autodesk Revit", "Voice Acting"],
    description:
      "Hi I'm Jose, and I'm a video editor and Voice Over Artist. With over 3+ years of experience, I have successfully completed numerous projects for clients worldwide.",
    buyerReviews: [
      {
        title: "Voice Over for Educational Content",
        rating: 5,
        date: "April 2, 2025",
        content:
          "Ojochegbe delivered exceptional voice over work for our educational videos. Clear pronunciation and professional delivery.",
        reviewer: "Educational Platform Inc.",
      },
    ],
    sellerReviews: [
      {
        title: "Responsive client",
        rating: 5,
        date: "March 15, 2025",
        content: "Great communication and clear feedback throughout the project.",
        reviewer: "Ojochegbe O.",
      },
    ],
  },
  {
    id: 5,
    name: "Sarah J.",
    title: "Professional Video Editor & Motion Graphics Designer",
    avatar: "/placeholder.svg?height=120&width=120",
    rating: 4.8,
    reviewCount: 45,
    jobSuccess: 95,
    hourlyRate: 30,
    isVerified: true,
    isAvailable: true,
    location: "United States",
    localTime: "2:10 pm",
    totalJobs: 37,
    totalHours: 120,
    totalEarned: "75K",
    skills: ["Video Editing", "Motion Graphics", "After Effects", "Premiere Pro", "Final Cut Pro"],
    description:
      "I'm a professional video editor with 7+ years of experience working with brands, content creators, and marketing agencies. I specialize in creating engaging and visually appealing content that drives engagement.",
    buyerReviews: [
      {
        title: "Corporate Video Editing",
        rating: 5,
        date: "April 10, 2025",
        content:
          "Sarah delivered exceptional work for our corporate video. Her attention to detail and creative input elevated the final product beyond our expectations.",
        reviewer: "Corporate Client",
      },
    ],
    sellerReviews: [
      {
        title: "Professional client",
        rating: 5,
        date: "March 20, 2025",
        content: "Clear communication and prompt payments. Would work with them again.",
        reviewer: "Sarah J.",
      },
    ],
  },
  {
    id: 6,
    name: "Michael T.",
    title: "Video Editor & Colorist",
    avatar: "/placeholder.svg?height=120&width=120",
    rating: 4.7,
    reviewCount: 38,
    jobSuccess: 92,
    hourlyRate: 35,
    isVerified: true,
    isAvailable: false,
    location: "Canada",
    localTime: "1:10 pm",
    totalJobs: 42,
    totalHours: 156,
    totalEarned: "90K",
    skills: ["Video Editing", "Color Grading", "DaVinci Resolve", "Premiere Pro", "After Effects"],
    description:
      "Professional video editor and colorist with 8+ years of experience in film, commercial, and online content. I focus on storytelling through visual editing and color to create impactful content.",
    buyerReviews: [
      {
        title: "Commercial Video Editing",
        rating: 5,
        date: "April 5, 2025",
        content:
          "Michael's color grading skills are exceptional. He transformed our commercial footage into a cinematic masterpiece.",
        reviewer: "Advertising Agency",
      },
    ],
    sellerReviews: [
      {
        title: "Great collaboration",
        rating: 5,
        date: "March 25, 2025",
        content: "The client had a clear vision and was open to creative suggestions. A pleasure to work with.",
        reviewer: "Michael T.",
      },
    ],
  },
  {
    id: 7,
    name: "Emma L.",
    title: "Social Media Video Editor",
    avatar: "/placeholder.svg?height=120&width=120",
    rating: 4.9,
    reviewCount: 52,
    jobSuccess: 98,
    hourlyRate: 25,
    isVerified: true,
    isAvailable: true,
    location: "United Kingdom",
    localTime: "7:10 pm",
    totalJobs: 56,
    totalHours: 210,
    totalEarned: "65K",
    skills: ["Social Media", "Video Editing", "TikTok", "Instagram Reels", "YouTube Shorts"],
    description:
      "Specialized in creating engaging short-form video content for social media platforms. I help brands and influencers maximize engagement through creative and trend-aware video editing.",
    buyerReviews: [
      {
        title: "TikTok Content Creation",
        rating: 5,
        date: "April 12, 2025",
        content:
          "Emma created a series of TikTok videos that helped us gain over 100K followers in just one month. Her understanding of trends and audience engagement is unmatched.",
        reviewer: "Fashion Brand",
      },
    ],
    sellerReviews: [
      {
        title: "Innovative client",
        rating: 5,
        date: "March 30, 2025",
        content: "The client had creative ideas and was open to experimentation. Great collaboration.",
        reviewer: "Emma L.",
      },
    ],
  },
  {
    id: 8,
    name: "David K.",
    title: "Documentary & Interview Video Editor",
    avatar: "/placeholder.svg?height=120&width=120",
    rating: 4.8,
    reviewCount: 30,
    jobSuccess: 94,
    hourlyRate: 40,
    isVerified: true,
    isAvailable: false,
    location: "Australia",
    localTime: "4:10 am",
    totalJobs: 31,
    totalHours: 180,
    totalEarned: "110K",
    skills: ["Documentary Editing", "Interview Editing", "Storytelling", "Premiere Pro", "Audio Editing"],
    description:
      "Experienced documentary and interview video editor with a background in journalism. I specialize in crafting compelling narratives from interview footage and documentary material.",
    buyerReviews: [
      {
        title: "Documentary Series Editing",
        rating: 5,
        date: "April 8, 2025",
        content:
          "David edited our 5-part documentary series with exceptional skill. His ability to weave together complex narratives from hours of footage is remarkable.",
        reviewer: "Production Company",
      },
    ],
    sellerReviews: [
      {
        title: "Professional collaboration",
        rating: 5,
        date: "March 15, 2025",
        content: "The client provided well-organized footage and clear direction. A pleasure to work with.",
        reviewer: "David K.",
      },
    ],
  },
]
